### ISSUE TITLE
RadioSpinelNoResponse using slae.sh CC2652R stick

### ISSUE THREAD

**Issue by El-mou33** [home-assistant/addons-development#38]
Im trying to set up a slae.shCC2652R stick with open thread firmware. I chosen the correct device and the correct baudrate. The error still happening.

When I start the web ui the page only says 502: Bad Gateway.

I didn't find any way to modify the front end port or something like zigbee2mqtt does.

**Comment by ludeeus** [comment]
502 usually means that the add-on did not start properly, check your add-on logs

**Comment by El-mou33** [comment]
I don't know exactly what happens but the logs repeat this several times:

setsockopt - SO_RECV_ANYIF: Protocol not available

Should I need to flash the OTBR before to use this addon?

**Comment by agners** [comment]
The `setsockopt` error is related to the mDNSResponder, but not harmful from what I can tell.

There was an error in the add-on when hardware flow control was off, I just merged a fix with #39. Can you try version 0.1.3 again?

It could also be that the border router firmware is too old, but I would expect some type of message in the logs.

**Comment by El-mou33** [comment]
This are the logs:

[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[13:02:43] INFO: Starting mDNS Responder...
mDNSResponder (Engineering Build) (Apr 19 2022 18:37:56) starting
setsockopt - SO_RECV_ANYIF: Protocol not available
setsockopt - SO_RECV_ANYIF: Protocol not available
setsockopt - SO_RECV_ANYIF: Protocol not available
setsockopt - SO_RECV_ANYIF: Protocol not available
setsockopt - SO_RECV_ANYIF: Protocol not available
setsockopt - SO_RECV_ANYIF: Protocol not available
setsockopt - SO_RECV_ANYIF: Protocol not available
mDNS_AddDNSServer: Lock not held! mDNS_busy (0) mDNS_reentrancy (0)
CheckNATMappings: Failed to allocate port 5350 UDP multicast socket for PCP & NAT-PMP announcements
[13:02:45] INFO: Starting otbr-agent...
otbr-agent[230]: [INFO]-UTILS---: Running 0.3.0-f8399eb-dirty
otbr-agent[230]: [INFO]-UTILS---: Thread version: 1.2.0
otbr-agent[230]: [INFO]-UTILS---: Thread interface: wpan0
otbr-agent[230]: [INFO]-UTILS---: Backbone interface: eth0
otbr-agent[230]: [INFO]-UTILS---: Radio URL: spinel+hdlc+uart:///dev/ttyUSB2?uart-baudrate=115200&uart-flow-control
setsockopt - SO_RECV_ANYIF: Protocol not available
setsockopt - SO_RECV_ANYIF: Protocol not available
setsockopt - SO_RECV_ANYIF: Protocol not available
setsockopt - SO_RECV_ANYIF: Protocol not available
setsockopt - SO_RECV_ANYIF: Protocol not available
setsockopt - SO_RECV_ANYIF: Protocol not available
setsockopt - SO_RECV_ANYIF: Protocol not available
otbr-agent[230]: 50d.00:21:03.461 [C] Platform------: BSD TCP function() at radio_spinel_impl.hpp:2236: RadioSpinelNoResponse
setsockopt - SO_RECV_ANYIF: Protocol not available
setsockopt - SO_RECV_ANYIF: Protocol not available
setsockopt - SO_RECV_ANYIF: Protocol not available
setsockopt - SO_RECV_ANYIF: Protocol not available
setsockopt - SO_RECV_ANYIF: Protocol not available
setsockopt - SO_RECV_ANYIF: Protocol not available
setsockopt - SO_RECV_ANYIF: Protocol not available
[13:03:17] INFO: otbr-agent ended with exit code 6 (signal 0)...
[13:03:18] INFO: Starting otbr-agent...
otbr-agent[415]: [INFO]-UTILS---: Running 0.3.0-f8399eb-dirty
otbr-agent[415]: [INFO]-UTILS---: Thread version: 1.2.0
otbr-agent[415]: [INFO]-UTILS---: Thread interface: wpan0
otbr-agent[415]: [INFO]-UTILS---: Backbone interface: eth0
otbr-agent[415]: [INFO]-UTILS---: Radio URL: spinel+hdlc+uart:///dev/ttyUSB2?uart-baudrate=115200&uart-flow-control

**Comment by agners** [comment]
Oh I see now:

>  otbr-agent[230]: 50d.00:21:03.461 [C] Platform------: BSD TCP function() at radio_spinel_impl.hpp:2236: RadioSpinelNoResponse

That issue is relate to missing network drivers. I've recently added them to all supported HAOS platforms: https://github.com/home-assistant/operating-system/pull/1870

What platform are you on? Can you try the latest dev build? You should be able to upgrade with something along these lines:

```
ha su options --channel=dev
ha su reload
ha os update --version=8.0.dev20220427
```

**Comment by El-mou33** [comment]
That's a problem for me I have Home assistant core and home assistant supervisor. I change to the latest development mode but that error still happening. I don't know if there is other way to get the drivers.

**Comment by agners** [comment]
@El-mou33 can you link me the firmware you have been using?

I've not tried TI sticks so far, so quite possible something is not working with that particular model. From the logs it seems the stick doesn't answer:

```
otbr-agent[230]: 50d.00:21:03.461 [C] Platform------: BSD TCP function() at radio_spinel_impl.hpp:2236: RadioSpinelNoResponse
```

**Comment by El-mou33** [comment]
I think here is the firmware:

[https://github.com/Koenkk/Z-Stack-firmware/tree/master/router/Z-Stack_3.x.0/bin](https://github.com/Koenkk/Z-Stack-firmware/tree/master/router/Z-Stack_3.x.0/bin)

Because Im not fully sure that's what you need, this is the page where I found that link and other instructions about firmware:

[https://slae.sh/projects/cc2652/](https://slae.sh/projects/cc2652/)

**Comment by agners** [comment]
> https://github.com/Koenkk/Z-Stack-firmware/tree/master/router/Z-Stack_3.x.0/bin

Those are Z-Stack firmwares, that is Zigbee so something else.

The OpenThread Border Router add-on is really built from recent upstream sources, and should work with any of the supported  RCP firmwares (as long as they work with the `spinel+hdlc+uart` protocol, and from what I understand the `CC2652R` should work with that protocol).

It seems that there is a OTBR firmware on [this page](https://slae.sh/projects/cc2652/#openthread-border-router), however, there is no date code or version information.

> At the end of the last link, they say they have telegram for technical support.

Yeah it's probably best if you contact him and ask what type of firmware that exactly is and with which version of OpenThread it has been built. Probably best to send him the link to this issue, so we can sort it out directly.

**Comment by El-mou33** [comment]
Ok I contacted him. This is what they said:


Looks like that this add-on expects an "RCP" device. But our firmware is currently an "NCP" ..

I will try to create another firmware for you 👍😎

**Comment by Hedda** [comment]
> Looks like that this add-on expects an "RCP" device. But our firmware is currently an "NCP" ..

Yeah you are at least going to need to build, compile and flash an "OpenThread Border Router (OTBR)" firmware for that adapter.

Also note that Texas Instruments CC2652-based adapters from different manufacturers do maybe not use the same pinout or use chips with the same storage site, so a firmware image file built for the [CC2652R-stick](https://github.com/slaesh/cc2652-stick) made by slaesh will not work on [Electrolama's zzh (zig-a-zig-ah) adapter](https://github.com/electrolama/zig-a-zig-ah) by omerk or the [ZigStar Stick V4](https://github.com/mercenaruss/zigbee-stick-v4) by mercenaruss and vice versa as all of those use slightly different pinout schematic for CC2652R, CC2652RB, and CC2652P GPIO pins and/or have a different sized firmware image. 

The same goes with other popular CC2652-based adapters, such as [cod.m ZigBee CC2652P Raspberry Pi module](https://github.com/codm/cc2652-raspberry-pi-module) and [cod.m ZigBee CC2652P2 TCP Coordinator](https://github.com/codm/cc2652p2-tcp-zigbee), [Gio-dot Z-Bee Duo](https://github.com/Gio-dot/Z-Bee-Duo), [Egony Stick V4](https://github.com/egony/cc2652p_E72-2G4M20S1E), and [Tube's Zigbee Gateways](https://github.com/tube0013/tube_gateways) which most will need images compiled specificly for their pinouts and size.

**Comment by El-mou33** [comment]
Ok I think I'm going to abandom. The problem persist even with new firmware. These are the logs:

> otbr-agent[6457]: 49d.22:39:57.734 [W] Platform------: Wait for response timeout
> otbr-agent[6457]: 49d.22:39:57.734 [C] Platform------: HandleRcpTimeout() at radio_spinel_impl.hpp:2229: RadioSpinelNoResponse
> [11:24:56] WARNING: No primary network interface found! Using static eth0.
> [11:24:56] INFO: Starting otbr-agent...
> otbr-agent[6511]: [NOTE]-AGENT---: Running 0.3.0-9fea68c-dirty
> otbr-agent[6511]: [NOTE]-AGENT---: Thread version: 1.2.0
> otbr-agent[6511]: [NOTE]-AGENT---: Thread interface: wpan0
> otbr-agent[6511]: [NOTE]-AGENT---: Backbone interface: eth0
> otbr-agent[6511]: [NOTE]-AGENT---: Radio URL: spinel+hdlc+uart:///dev/ttyUSB1?uart-baudrate=115200
> otbr-agent[6511]: [INFO]-NCP-----: OpenThread log level changed to 4
> otbr-agent[6511]: 49d.22:40:01.087 [W] Platform------: Wait for response timeout
> otbr-agent[6511]: 49d.22:40:01.087 [C] Platform------: HandleRcpTimeout() at radio_spinel_impl.hpp:2229: RadioSpinelNoResponse
> [11:24:59] WARNING: No primary network interface found! Using static eth0.
> [11:24:59] INFO: Starting otbr-agent...
> otbr-agent[6565]: [NOTE]-AGENT---: Running 0.3.0-9fea68c-dirty
> otbr-agent[6565]: [NOTE]-AGENT---: Thread version: 1.2.0
> otbr-agent[6565]: [NOTE]-AGENT---: Thread interface: wpan0
> otbr-agent[6565]: [NOTE]-AGENT---: Backbone interface: eth0
> otbr-agent[6565]: [NOTE]-AGENT---: Radio URL: spinel+hdlc+uart:///dev/ttyUSB1?uart-baudrate=115200
> otbr-agent[6565]: [INFO]-NCP-----: OpenThread log level changed to 4
> otbr-agent[6565]: 49d.22:40:04.385 [W] Platform------: Wait for response timeout
> otbr-agent[6565]: 49d.22:40:04.385 [C] Platform------: HandleRcpTimeout() at radio_spinel_impl.hpp:2229: RadioSpinelNoResponse
> [11:25:02] WARNING: No primary network interface found! Using static eth0.
> [11:25:02] INFO: Starting otbr-agent...
> otbr-agent[6619]: [NOTE]-AGENT---: Running 0.3.0-9fea68c-dirty
> otbr-agent[6619]: [NOTE]-AGENT---: Thread version: 1.2.0
> otbr-agent[6619]: [NOTE]-AGENT---: Thread interface: wpan0
> otbr-agent[6619]: [NOTE]-AGENT---: Backbone interface: eth0
> otbr-agent[6619]: [NOTE]-AGENT---: Radio URL: spinel+hdlc+uart:///dev/ttyUSB1?uart-baudrate=115200
> otbr-agent[6619]: [INFO]-NCP-----: OpenThread log level changed to 4
> otbr-agent[6619]: 49d.22:40:07.646 [W] Platform------: Wait for response timeout
> otbr-agent[6619]: 49d.22:40:07.647 [C] Platform------: HandleRcpTimeout() at radio_spinel_impl.hpp:2229: RadioSpinelNoResponse
> [11:25:05] WARNING: No primary network interface found! Using static eth0.
> [11:25:06] INFO: Starting otbr-agent...
> otbr-agent[6673]: [NOTE]-AGENT---: Running 0.3.0-9fea68c-dirty
> otbr-agent[6673]: [NOTE]-AGENT---: Thread version: 1.2.0
> otbr-agent[6673]: [NOTE]-AGENT---: Thread interface: wpan0
> otbr-agent[6673]: [NOTE]-AGENT---: Backbone interface: eth0
> otbr-agent[6673]: [NOTE]-AGENT---: Radio URL: spinel+hdlc+uart:///dev/ttyUSB1?uart-baudrate=115200
> otbr-agent[6673]: [INFO]-NCP-----: OpenThread log level changed to 4
> otbr-agent[6673]: 49d.22:40:10.898 [W] Platform------: Wait for response timeout
> otbr-agent[6673]: 49d.22:40:10.899 [C] Platform------: HandleRcpTimeout() at radio_spinel_impl.hpp:2229: RadioSpinelNoResponse
> [11:25:09] WARNING: No primary network interface found! Using static eth0.
> [11:25:09] INFO: Starting otbr-agent...
> otbr-agent[6727]: [NOTE]-AGENT---: Running 0.3.0-9fea68c-dirty
> otbr-agent[6727]: [NOTE]-AGENT---: Thread version: 1.2.0
> otbr-agent[6727]: [NOTE]-AGENT---: Thread interface: wpan0
> otbr-agent[6727]: [NOTE]-AGENT---: Backbone interface: eth0
> otbr-agent[6727]: [NOTE]-AGENT---: Radio URL: spinel+hdlc+uart:///dev/ttyUSB1?uart-baudrate=115200
> otbr-agent[6727]: [INFO]-NCP-----: OpenThread log level changed to 4
> otbr-agent[6727]: 49d.22:40:14.179 [W] Platform------: Wait for response timeout
> otbr-agent[6727]: 49d.22:40:14.179 [C] Platform------: HandleRcpTimeout() at radio_spinel_impl.hpp:2229: RadioSpinelNoResponse
> [11:25:12] WARNING: No primary network interface found! Using static eth0.
> [11:25:12] INFO: Starting otbr-agent...
> otbr-agent[6781]: [NOTE]-AGENT---: Running 0.3.0-9fea68c-dirty
> otbr-agent[6781]: [NOTE]-AGENT---: Thread version: 1.2.0
> otbr-agent[6781]: [NOTE]-AGENT---: Thread interface: wpan0
> otbr-agent[6781]: [NOTE]-AGENT---: Backbone interface: eth0
> otbr-agent[6781]: [NOTE]-AGENT---: Radio URL: spinel+hdlc+uart:///dev/ttyUSB1?uart-baudrate=115200
> otbr-agent[6781]: [INFO]-NCP-----: OpenThread log level changed to 4
> otbr-agent[6781]: 49d.22:40:17.395 [W] Platform------: Wait for response timeout
> otbr-agent[6781]: 49d.22:40:17.395 [C] Platform------: HandleRcpTimeout() at radio_spinel_impl.hpp:2229: RadioSpinelNoResponse
> [11:25:15] WARNING: No primary network interface found! Using static eth0.
> [11:25:15] INFO: Starting otbr-agent...
> otbr-agent[6835]: [NOTE]-AGENT---: Running 0.3.0-9fea68c-dirty
> otbr-agent[6835]: [NOTE]-AGENT---: Thread version: 1.2.0
> otbr-agent[6835]: [NOTE]-AGENT---: Thread interface: wpan0
> otbr-agent[6835]: [NOTE]-AGENT---: Backbone interface: eth0
> otbr-agent[6835]: [NOTE]-AGENT---: Radio URL: spinel+hdlc+uart:///dev/ttyUSB1?uart-baudrate=115200
> otbr-agent[6835]: [INFO]-NCP-----: OpenThread log level changed to 4
> otbr-agent[6835]: 49d.22:40:20.669 [W] Platform------: Wait for response timeout
> otbr-agent[6835]: 49d.22:40:20.669 [C] Platform------: HandleRcpTimeout() at radio_spinel_impl.hpp:2229: RadioSpinelNoResponse
> [11:25:18] WARNING: No primary network interface found! Using static eth0.
> [11:25:18] INFO: Starting otbr-agent...
> otbr-agent[6889]: [NOTE]-AGENT---: Running 0.3.0-9fea68c-dirty
> otbr-agent[6889]: [NOTE]-AGENT---: Thread version: 1.2.0
> otbr-agent[6889]: [NOTE]-AGENT---: Thread interface: wpan0
> otbr-agent[6889]: [NOTE]-AGENT---: Backbone interface: eth0
> otbr-agent[6889]: [NOTE]-AGENT---: Radio URL: spinel+hdlc+uart:///dev/ttyUSB1?uart-baudrate=115200
> otbr-agent[6889]: [INFO]-NCP-----: OpenThread log level changed to 4
> otbr-agent[6889]: 49d.22:40:23.866 [W] Platform------: Wait for response timeout
> otbr-agent[6889]: 49d.22:40:23.866 [C] Platform------: HandleRcpTimeout() at radio_spinel_impl.hpp:2229: RadioSpinelNoResponse
> [11:25:22] WARNING: No primary network interface found! Using static eth0.
> [11:25:22] INFO: Starting otbr-agent...
> otbr-agent[6943]: [NOTE]-AGENT---: Running 0.3.0-9fea68c-dirty
> otbr-agent[6943]: [NOTE]-AGENT---: Thread version: 1.2.0
> otbr-agent[6943]: [NOTE]-AGENT---: Thread interface: wpan0
> otbr-agent[6943]: [NOTE]-AGENT---: Backbone interface: eth0
> otbr-agent[6943]: [NOTE]-AGENT---: Radio URL: spinel+hdlc+uart:///dev/ttyUSB1?uart-baudrate=115200
> otbr-agent[6943]: [INFO]-NCP-----: OpenThread log level changed to 4
> otbr-agent[6943]: 49d.22:40:27.185 [W] Platform------: Wait for response timeout
> otbr-agent[6943]: 49d.22:40:27.185 [C] Platform------: HandleRcpTimeout() at radio_spinel_impl.hpp:2229: RadioSpinelNoResponse
> [11:25:25] WARNING: No primary network interface found! Using static eth0.
> [11:25:25] INFO: Starting otbr-agent...
> otbr-agent[6997]: [NOTE]-AGENT---: Running 0.3.0-9fea68c-dirty
> otbr-agent[6997]: [NOTE]-AGENT---: Thread version: 1.2.0
> otbr-agent[6997]: [NOTE]-AGENT---: Thread interface: wpan0
> otbr-agent[6997]: [NOTE]-AGENT---: Backbone interface: eth0
> otbr-agent[6997]: [NOTE]-AGENT---: Radio URL: spinel+hdlc+uart:///dev/ttyUSB1?uart-baudrate=115200
> otbr-agent[6997]: [INFO]-NCP-----: OpenThread log level changed to 4

**Comment by Hedda** [comment]
@El-mou33 Can I suggest that you edit/change your original to be a little more generic to include all TI CC2652-based adapters?

Suggestion: "**_Thread Spinel RPC firmware for Texas Instruments CC2652 to use OpenThread Border Router (OTBR) Add-on?_**"

**Comment by Hedda** [comment]
> PS: This discussion should probably also be moved from issues here to a new thread in the Home Assistant's community forum?

FYI, I started a new discussion thread in Home Assistant's community forum to discuss OTBR RPC firmware for CC2652/CC1352:

https://community.home-assistant.io/t/thread-spinel-rpc-firmware-for-texas-instruments-cc2652-cc1352-to-use-openthread-border-router-otbr-add-on-for-use-with-thread-based-devices-like-some-future-matter-chip-products/433278

@agners That dicussion is posted under the Zigbee section now so maybe can move once create a Thread/OpenThread section?

**Comment by tube0013** [comment]
the current RPC FW and OTBR build need to come from the same OT versions - down to commit, you can see this in the Matter examples from the SI Labs knowledge bates <https://community.silabs.com/s/article/Matter-getting-start-guide?language=en_US>

The multi-protocol implementation relies on the SI Labs stack. I found a stale PR from them that I think would bring the function to the main OT implementation which potentially could mean a compatible RPC fw for multi-protocol could work with TI or Noridic or ... radios. <https://github.com/openthread/openthread/pull/6258>

**Comment by Hedda** [comment]
> the current RPC FW and OTBR build need to come from the same OT versions - down to commit to work best. You can see this in the Matter examples from the SI Labs knowledge bates https://community.silabs.com/s/article/Matter-getting-start-guide?language=en_US
> 
> The multi-protocol implementation relies on the SI Labs stack. I found a stale PR from them that I think would bring the function to the main OT implementation which potentially could mean a compatible RPC fw for multi-protocol could work with TI or Noridic or ... radios. [openthread/openthread#6258](https://github.com/openthread/openthread/pull/6258)

@agners Will your "[OpenThread Border Router Add-on](https://github.com/home-assistant/addons-development/tree/master/openthread_border_router)" be compatible with all and any manufacturers/model/brand of 802.15.4 SoC platforms with OTBR firmware as long as it supports RCP with Spinel or does it also have to be a specific OpenThread version?

https://openthread.io/platforms

As I understand the only important requirement is that the firmware build uses OpenThread's standard RCP (Radio Co-Processor) design with Spinel serial protocol for communicating between it and the host, as there is no mention of OpenThread version?

https://openthread.io/platforms/co-processor

Also, the multi-protocol implementation with Zigee support is not required if a user only wants to use Thread (and Matter) and the firmware is not multi-protocol so the adapter is only flashed with a pure OpenThread RPC Spinel application firmware?

**Comment by agners** [comment]
> @agners Will your "[OpenThread Border Router Add-on](https://github.com/home-assistant/addons-development/tree/master/openthread_border_router)" be compatible with all manufacturers/models of 802.15.4 SoC platforms as long as has OTBR RCP firmware with Spinel or does it also have to be a specific OpenThread version and/or radio version?

Generally yes, as long as the RCP firmware with Spinel uses the upstream/official Spinel implementation.

> 
> https://openthread.io/platforms
> 
> I thought the only important requirement is that firmware build uses OpenThread's standard RCP (Radio Co-Processor) design with Spinel serial protocol for communicating with the host as there is no mention of OpenThread version and/or radio version?

The RCP API does change from time to time, but it is fairly stable and moves fairly slowly. Also, the host (add-on) supports multiple API versions (backwards compatible to some degree). So an older firmware is quite likely to work with a newer OTRB.

See also:
https://github.com/openthread/openthread/blob/main/src/lib/spinel/spinel.h#L369-L392

> 
> https://openthread.io/platforms/co-processor
> 
> PS: Slightly off-topic but FYI, I believe that the ZHA integration gained a lot of additional users and developers because its devs added support for hardware adapters from many manufacturers/stacks and all protocol versions for those so that it today is both hardware independent and FW backwards compatible -> https://www.home-assistant.io/integrations/zha#compatible-hardware

:+1:

**Comment by Hedda** [comment]
FYI, missed that tube0013 posted on Twitter that be uploaded OpenThread RCP firmware images for the CC2652P (TubesZB devices) CC2652R (zzh!) that could be used for development and testing as he confirmed those working with agners OTBR addon from addons-development so that could be of interest for those early adopters interested in Thread/Matter support inside Home Assistant:

https://twitter.com/TubesZb/status/1552823766136373251

https://github.com/tube0013/tube_gateways/tree/main/openthread_boarder_router_fw

**Comment by Hedda** [comment]
Suppose those should now cover most CC2652P, CC2652R, and CC2652RB based devices that follow the community pin standard?

* https://github.com/tube0013/tube_gateways/blob/main/openthread_boarder_router_fw/rcp_LP_CC2652PSIP_tirtos_ticlang.hex.zip should be compatible with those that support flashing "**_CC1352P2_CC2652P_launchpad_*.zip_**"
* https://github.com/tube0013/tube_gateways/blob/main/openthread_boarder_router_fw/rcp_CC26X2R1_LAUNCHXL_tirtos_ticlang.hex.zip should be compatible with those that support flashing "**_CC2652R_*.zip_**"
* https://github.com/slaesh/cc2652-stick/files/9792866/rcp_CC2652RB_115200_v6.20.00.29.bin.zip should be compatible with those that support flashing "**_CC2652RB_*.zip_**"

**Warning!** Note that flashing any OpenThread  firmware images you will loose your Zigbee network if you been using it for that! Also make sure you flash the correct firmware! Flashing the wrong firmware might lock your bootloader preventing future flashing, meaning that flashing the wrong firmware image can brick your device and need to buy a [cJTAG adapter to manually flash](https://electrolama.com/radio-docs/advanced/flash-jtag/) it in order to unbrick it.

https://github.com/Koenkk/Z-Stack-firmware/blob/develop/coordinator/Z-Stack_3.x.0/bin/README.md

<table>
<thead>
  <tr>
    <th>Adapter</th>
    <th>TI Chip/Module Used</th>
    <th>Firmware to Flash</th>
    <th>BSL Trigger Pin (1)</th>
    <th>Auto-BSL (2)</th>
    <th>RF Switch Control Pins (3)</th>
    <th>LED(s)</th>
    <th>Hardware Flow Control</th>
  </tr>
</thead>
<tbody>
  <tr>
    <td>TI LAUNCHXL-CC26xR1</td>
    <td>CC2652R</td>
    <td>CC2652R_*.zip<br></td>
    <td>DIO_13</td>
    <td>No</td>
    <td>N/A</td>
    <td>DIO_6 (Red)<br>DIO_7 (Green)<br></td>
    <td>?</td>
  </tr>
  <tr>
    <td>TI LAUNCHXL-CC1352P-2</td>
    <td>CC1352P</td>
    <td>CC1352P2_CC2652P_launchpad_*.zip</td>
    <td>DIO_15</td>
    <td>No</td>
    <td>DIO_28: 2.4Ghz<br>DIO_29: 20dBm PA<br>DIO_30: Sub-1GHz</td>
    <td>DIO_6 (Red)<br>DIO_7 (Green)<br></td>
    <td>?</td>
  </tr>
  <tr>
    <td>Electrolama zzh</td>
    <td>CC2652R</td>
    <td>CC2652R_*.zip</td>
    <td>DIO_13</td>
    <td>No</td>
    <td>N/A</td>
    <td>DIO_7 (Pink)</td>
    <td>?</td>
  </tr>
  <tr>
    <td>Slaesh's CC2652RB stick</td>
    <td>CC2652RB</td>
    <td>CC2652RB_*.zip</td>
    <td>DIO_13</td>
    <td>Yes</td>
    <td>N/A</td>
    <td>DIO_7 (Blue)</td>
    <td>?</td>
  </tr>
  <tr>
    <td><a href="https://zig-star.com">ZigStar Stick v4</a></td>
    <td>CC2652P<br>(RFSTAR RF-BM-2652P2)<br></td>
    <td>CC1352P2_CC2652P_launchpad_*.zip</td>
    <td>DIO_15</td>
    <td>Only for CH340C ver.</td>
    <td>DIO_28: 2.4Ghz<br>DIO_29: 20dBm PA</td>
    <td>DIO_6 (Green)<br>DIO_7 (Red)<br></td>
    <td>?</td>
  </tr>
  <tr>
    <td>CircuitSetup.us Zigbee Stick</a></td>
    <td>CC2652P<br>(RFSTAR RF-BM-2652P2 PCB Ant.)<br></td>
    <td>CC1352P2_CC2652P_launchpad_*.zip</td>
    <td>DIO_15</td>
    <td>No</td>
    <td>DIO_28: 2.4Ghz<br>DIO_29: 20dBm PA</td>
    <td>DIO_6 (Green)<br>DIO_7 (Red)<br></td>
    <td>?</td>
  </tr>
  <tr>
    <td>Tube's CC2652P2 USB Coordinator<br></td>
    <td>CC2652P<br>(RFSTAR RF-BM-2652P2)<br></td>
    <td>CC1352P2_CC2652P_launchpad_*.zip</td>
    <td>DIO_15</td>
    <td>N/A</td>
    <td>DIO_28: 2.4Ghz<br>DIO_29: 20dBm PA</td>
    <td>N/A</td>
    <td>?</td>
  </tr>
  <tr>
    <td>Tube's Zigbee Gateways (CC2652P2 variant)<br></td>
    <td>CC2652P<br>(RFSTAR RF-BM-2652P2)<br></td>
    <td>CC1352P2_CC2652P_launchpad_*.zip</td>
    <td>DIO_15</td>
    <td>N/A</td>
    <td>DIO_28: 2.4Ghz<br>DIO_29: 20dBm PA</td>
    <td>N/A</td>
    <td>?</td>
  </tr>
  <tr>
    <td>Tube's Zigbee PoE (Power Over Ethernet) Serial Coordinator (CC2652P2 variant)<br></td>
    <td>CC2652P<br>(RFSTAR RF-BM-2652P2)<br></td>
    <td>CC1352P2_CC2652P_launchpad_*.zip</td>
    <td>DIO_15</td>
    <td>N/A</td>
    <td>DIO_28: 2.4Ghz<br>DIO_29: 20dBm PA</td>
    <td>N/A</td>
    <td>?</td>
  </tr>
  <tr>
    <td>Egony Stick V4<br>(RFSTAR ver.)</td>
    <td>CC2652P<br>(RFSTAR RF-BM-2652P2)</td>
    <td>CC1352P2_CC2652P_launchpad_*.zip</td>
    <td>DIO_15</td>
    <td>Yes</td>
    <td>DIO_28: 2.4Ghz<br>DIO_29: 20dBm PA</td>
    <td>DIO_7 (Green)<br>DIO_6 (Red)<br></td>
    <td>?</td>
  </tr>
  <tr>
  <td><a href="https://github.com/codm/cc2652-raspberry-pi-module">cod.m Zigbee CC2652P RPi Module</a></td>
    <td>CC2652P<br>(RFSTAR RF-BM-2652P2)</td>
    <td>CC1352P2_CC2652P_launchpad_*.zip</td>
    <td>DIO_15</td>
    <td>No</td>
    <td>DIO_28: 2.4Ghz<br>DIO_29: 20dBm PA</td>
    <td>N/A</td>
    <td>?</td>
  </tr>
  <tr>
    <td><a href="https://github.com/codm/cc2652p2-tcp-zigbee">cod.m ZigBee CC2652P2 TCP Coordinator</a></td>
    <td>CC2652P<br>(RFSTAR RF-BM-2652P2)</td>
    <td>CC1352P2_CC2652P_launchpad_*.zip</td>
    <td>DIO_15</td>
    <td>No</td>
    <td>DIO_28: 2.4Ghz<br>DIO_29: 20dBm PA</td>
    <td>DIO_7 (Green)<br>DIO_6 (Red)<br></td>
    <td>?</td>
  </tr>
  <tr>
    <td><a href="https://github.com/Gio-dot/Z-Bee-Duo">Gio-dot Z-Bee Duo with CC2652P</a></td>
    <td>CC2652P<br>(RFSTAR RF-BM-2652P2)<br></td>
    <td>CC1352P2_CC2652P_launchpad_*.zip</td>
    <td>DIO_15</td>
    <td>Yes</td>
    <td>DIO_28: 2.4Ghz<br>DIO_29: 20dBm PA</td>
    <td>DIO_7 (Green)<br>DIO_6 (Red)<br></td>
    <td>?</td>
  </tr>
  <tr>
    <td>cyijun <a href="https://github.com/cyijun/OpenZ3Gateway">OpenZ3Gateway</a></td>
    <td>CC2652P<br>(RFSTAR RF-BM-2652P2 SMA Ant.)<br></td>
    <td>CC1352P2_CC2652P_launchpad_*.zip</td>
    <td>DIO_15</td>
    <td>No</td>
    <td>DIO_28: 2.4Ghz<br>DIO_29: 20dBm PA</td>
    <td>DIO_7 (Green)<br>DIO_6 (Red)<br></td>
    <td>?</td>
  </tr>
  <tr>
    <td>SONOFF Zigbee 3.0 USB Dongle Plus by ITead</td>
    <td>CC2652P</td>
    <td>CC1352P2_CC2652P_launchpad_*.zip</td>
    <td>DIO_15</td>
    <td>Yes</td>
    <td>DIO_29: 20dBm PA</td>
    <td>DIO_7(Not welded)<br>Power LED(Red)</td>
    <td>DIO13: TX<br>DIO12:RC<br>DIO19: CTS(DIP switch ON)<br>DIO18: RTS(DIP switch ON)</td>
  </tr>
</tbody>
</table>

**Comment by Hedda** [comment]
@agners slightly off-topic but FYI, there is now an official experimental OTBR firmware available from dresden-elektronik for ConBee II and RaspBee II, see → https://github.com/dresden-elektronik/openthread-r21

**Comment by Hedda** [comment]
Has anyone successfully tested a compatible Texas Instruments OpenThread RCP firmware on a CC2652-based adapter as a TBR (Thread Border Router) with Home Assistant to create a Thread network that is used with Matter devices in official integration?

https://github.com/home-assistant/addons-development/tree/master/openthread_border_router

https://www.home-assistant.io/blog/2023/02/08/state-of-matter-and-thread/

https://www.home-assistant.io/blog/2023/03/01/release-20233/#thread--matter

https://www.home-assistant.io/integrations/thread

https://www.home-assistant.io/integrations/matter

**Comment by agners** [comment]
Since the add-on moved to the main repository at https://github.com/home-assistant/addons/tree/master/openthread_border_router now, this is the wrong place to discuss vanilla OTBR firmwares.

In any case, the issue tracker is probably the wrong place as well to discuss firmwares, unless there is a specific problem with a firmware which seems to be caused by the add-on itself. otherwise I'd suggest to discuss this elsewhere, maybe in the [community forums](https://community.home-assistant.io/).

**Comment by Hedda** [comment]
FYI, Texas Instruments now provide an official TI OpenThread project here which has to be compiled for each specific adapter

https://github.com/TexasInstruments/ot-ti

slaesh posted links to binaries for his cc2652 stick in this issue:

https://github.com/slaesh/cc2652-stick/issues/23

**Comment by martin3000** [comment]
The firmware is here: https://github.com/Koenkk/OpenThread-TexasInstruments-firmware/releases
For the slaesh-stick it should be the CC2652RB_ot_rcp_2025_3_1.zip
